#Auth user

POST http://hillel.api/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "lucas70@example.org",
    "token": "RZy00SDdXJ1ItshVeJ3v2c0ccj94yKyd",
    "device_name": "Samsung-FT1000"
}

###
POST http://hillel.api/api/auth/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer 3|ZICgiLWkaxiQs8gSrxdEqqKOu24k0WLeEuZfuIP3

###

GET http://hillel.api/api/user
Accept: application/json
Authorization: Bearer 3|ZICgiLWkaxiQs8gSrxdEqqKOu24k0WLeEuZfuIP3

###



# USERS
# Add users (create & add an email with verification token (plain text) to queue)

POST http://hillel.api/api/users
Accept: application/json
Content-Type: application/json

{
    "name": "user3 users1",
    "email": "user4@gmail.com",
    "country_id": "1"
}

###

# Verify user

#GET http://hillel.api/api/users/8/verify?token=2wQFXqiozZBjQE0vQlH8wol3e0Pyd4m1
#Accept: application/json

###

# List users (filter by name OR/AND email OR/AND verified OR/AND country)
#?name=&email=&verified=&country=
GET http://hillel.api/api/users
Accept: application/json
Authorization: Bearer 3|ZICgiLWkaxiQs8gSrxdEqqKOu24k0WLeEuZfuIP3

###

# Edit users

PUT http://hillel.api/api/users/20
Accept: application/json
Content-Type: application/json
Authorization: Bearer 3|ZICgiLWkaxiQs8gSrxdEqqKOu24k0WLeEuZfuIP3

{
    "name": "user111",
    "email": "user111@gmail.com",
    "country_id": "1"
}

###

# Delete users

DELETE http://hillel.api/api/users/19
Accept: application/json
Content-Type: application/json
Authorization: Bearer 3|ZICgiLWkaxiQs8gSrxdEqqKOu24k0WLeEuZfuIP3

###
###
###

# PROJECTS
# Add projects

POST http://hillel.api/api/projects
Accept: application/json
Content-Type: application/json
Authorization: Bearer 3|ZICgiLWkaxiQs8gSrxdEqqKOu24k0WLeEuZfuIP3

{
    "name": "project_6",
    "author_id": "3"
}

###

# Link projects to users

POST http://hillel.api/api/projects/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer 3|ZICgiLWkaxiQs8gSrxdEqqKOu24k0WLeEuZfuIP3

[
    3,
    7,
    6
]

###

# List projects incl. labels (filter by user.email OR/AND user.continent OR/AND labels)
#  filter[user_email]=&filter[user_continent]=&filter[labels]=
GET http://hillel.api/api/projects?user_continent=AF
Accept: application/json
Authorization: Bearer 3|ZICgiLWkaxiQs8gSrxdEqqKOu24k0WLeEuZfuIP3

###

# Delete projects

DELETE http://hillel.api/api/projects/40
Accept: application/json
Authorization: Bearer 3|ZICgiLWkaxiQs8gSrxdEqqKOu24k0WLeEuZfuIP3


###
###
###

# LABELS
# Add labels

POST http://hillel.api/api/labels
Accept: application/json
Content-Type: application/json
Authorization: Bearer 3|ZICgiLWkaxiQs8gSrxdEqqKOu24k0WLeEuZfuIP3

{
    "name": "label2",
    "author_id": "5"
}

###

# Link labels to projects

POST http://hillel.api/api/labels/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer 3|ZICgiLWkaxiQs8gSrxdEqqKOu24k0WLeEuZfuIP3

[
    5,
    7,
    8
]

###

# List labels (filter by user.email OR/AND projects)
# filter[user_email]=&filter[projects]=
GET http://hillel.api/api/labels?user_email=mable13@example.net
Accept: application/json
Authorization: Bearer 3|ZICgiLWkaxiQs8gSrxdEqqKOu24k0WLeEuZfuIP3

###

# Delete labels

DELETE http://hillel.api/api/labels/1
Accept: application/json
Authorization: Bearer 3|ZICgiLWkaxiQs8gSrxdEqqKOu24k0WLeEuZfuIP3

###
